### ISSUE TITLE
4px Bottom margin in container around canvas

### ISSUE THREAD

**Issue by E-Feng** [Gherciu/react-p5#15]
There seems to be a 4px bottom margin in the react-p5 div surrounding the canvas. This is creating overflow when I try to make the entire window the canvas.

The sandbox code shows the height of the div at 204px.

Thanks!

**Comment by Gherciu** [comment]
Hi @E-Feng , `react-p5` doesn't add any styles to the `.react-p5` class or to another div's or elements in your app or to `react-p5` div surrounding the canvas. It seems like you need to normalize your CSS files or recheck in your CSS files if you accidentally added a wrong style to the all div's in your app.
But if you do not find any mistake in your CSS files you can add a `styele={{margin: '0px'}}` prop in order to remove all margins from this div.

**Comment by E-Feng** [comment]
Hi,

Sorry for saying margin but I don't believe it's a margin issue. I have global margins at 0 and have tried the style of 0px margin.

The outer react-p5 div has an extra 4px on the bottom of the canvas.

![Untitled](https://user-images.githubusercontent.com/14305641/74176472-be54d700-4c05-11ea-8e56-93c97abc9f0e.png)

Is there an easy way to remove this extra 4px?

**Comment by Gherciu** [comment]
@E-Feng try this:
1) In your css files add this:
```css
.react-p5 canvas {
  margin: 0px;
  padding: 0px;
}
```
OR
```css
.react-p5 canvas {
  margin: 0px;
  padding: 0px;
}
```

OR in your render add a style prop:
```jsx
  <Scketch  style={{margin: 0, padding: 0}} />
```

Almost one example should work 100%;

**Comment by Gherciu** [comment]
@E-Feng  I tried this in a code sandbox and works fine:
```css
.react-p5 {
  display: flex;
}
```

**Comment by E-Feng** [comment]
Works great, thanks a lot!

**Comment by jamieweavis** [comment]
This is an issue the `<canvas>`  element, if you set `display: block;` on the canvas then the gap will disappear, for further reading: https://stackoverflow.com/a/15810161/1872666

**Comment by jamieweavis** [comment]
@E-Feng this is because the `<canvas>` HTML element has a display mode of `inline` which causes an extra line of whitespace to be rendered after the canvas element - this can be fixed this by styling the canvas to have a display mode of `block`.

As pointed out by @Gherciu `flex` will also work because it acts as a `block` level element.

**Comment by Gherciu** [comment]
@jamieweavis Thanks for a more detailed explanation, I think display `inline` is a better idea than the `flex` because `inline` is maintained by old browsers ;)
