### ISSUE TITLE
mousePressed event returns Undefined

### ISSUE THREAD

**Issue by bkawk** [Gherciu/react-p5#16]
Description:
https://stackoverflow.com/questions/60222225/p5-js-mousepressed-event-returns-undefined
CodeSandbox:
https://codesandbox.io/embed/withered-monad-jrhyw

**Comment by Gherciu** [comment]
@bkawk You should use the mousePressed method as a prop, so try and define it outside of setup and then pass it:
```
const App = () => {

const setup = (p5, parent) => {
  p5.createCanvas(200, 200).parent(parent);
}

const draw = p5 => {
  p5.background(0);
}

const mousePressed = p5 => {
   p5.fill(255);
   p5.ellipse(p5.mouseX, p5.mouseY, 20);
}
return  <Scketch setup={setup} draw={draw} mousePressed={mousePressed} />
};
```
But if you want to listen events on DOM elements not canvas element use pls native js event listeners.
Or can you pls provide more info about why you need mouse event in P5.js ?? In order to help you to resolve our issue.

**Comment by bkawk** [comment]
I have updated the codepen as you suuggested above, the mousePressed does not fire and draw an ellipse at the mouse location. 

I am also keen to know how to get the deltaY of the mouseWheel using props

https://codesandbox.io/embed/withered-monad-jrhyw

**Comment by Gherciu** [comment]
@bkawk  The ellipses are not drawn in your case because you need to move `p5.background()` in `setup` method. Pls, reread how p5 draw process work.

**Comment by Gherciu** [comment]
@bkawk I've made some changes and if you'll update to the latest version. Now you can get the event by accessing the second arg) 
```js
mouseClicked(_p5, event) {
  console.log(event)
}
```
