### ISSUE TITLE
MouseDragged/MousePressed/MouseReleased etc outside of canvas

### ISSUE THREAD

**Issue by IcyTv** [Gherciu/react-p5#41]
Hi,

So this might be down to wrong usage, but I have a problem:
I want to use the p5 mouse/touch event stuff in order for my user to be able to interact with the canvas. I also have other Components on the same page. When I now register a listener for these events, it always executes, even outside of the canvas bounds. Is this an issue on your end? Or a p5 issue? Does it come down to wrong usage?

Thank you for your time

**Comment by Gherciu** [comment]
@IcyTv did you used `parent` to render the canvas or not??

**Comment by Gherciu** [comment]
maybe is a issue related to wrong usage

**Comment by Hahlh** [comment]
Good day @Gherciu !

I hope you are doing great.

I face a similar issue and have declared the canvas exactly as stated in the docs:

```
canvas = p5.createCanvas(width, height).parent(canvasParentRef)
```

What can I do to debug this issue?
I tried so far to find the specific event in both the Chrome and Firefox devtools, but unfortunately without success.
Which is akward, since the event triggers everywhere on the page and that should mean, that it is attached to html, body or some wrapper element?

How can I identify the specific event in the devtools?

**Comment by Hahlh** [comment]
Is it correct, that events always get attached to the global p5 object?

See: 
https://github.com/Gherciu/react-p5/blob/82a5086934a35c5f3adacf098f7ab9743b026646/src/index.js#L37-L43

[According to this comment by Lauren Lee McCarthy](https://github.com/processing/p5.js/issues/1437#issuecomment-222509577) it would be necessary to attach the event to the canvas directly instead of the p5 object.

So far I have had no luck with attaching an event listener to the canvas and the `react-p5` wrapper. Those events get added successfully, but simply don't fire. 


**On a side note:**
There is also just a limited set of events being passed through as props: 
https://github.com/Gherciu/react-p5/blob/82a5086934a35c5f3adacf098f7ab9743b026646/src/index.js#L16-L36

It seems that all events that p5 allows could be used, if 
1. the whole list of available events is used or
2. the props name is passed through and simply assigned to p5 making it the users responsibility to work with the correct prop names. Would that require an additional error check?

**Comment by Gherciu** [comment]
@Hahlh It seems that this is an error from the `p5` library not from `react-p5` because in this wrapper I did not attach events to the `window` or `document`.......all events are handled by `p5`(
I'll try today to debug it and find a way how to fix it maybe is a problem with the used `p5` version.

About the list of events .....yes this list is not full, unfortunately.
But if someone wants to find and add there the remaining events, it will be nice and I will immediately merge and publish a new version.

**Comment by Hahlh** [comment]
@Gherciu  Thank you for your incredibly fast reply!

P5js 1.3.0 got released 14 days ago. Do you think everything should be compatible?

**Comment by Gherciu** [comment]
@Hahlh yes everything should be compatible because they didn't introduce breaking changes......
But I'm investigating this behaviour now, maybe I will found the problem.

**Comment by Hahlh** [comment]
Regarding the attached events not firing:

I resolved this by setting the z-index of the canvas element to 50 and position to relative (to make z-index work) and manually attaching an event listener to the canvas:

```javascript
const setup = (p5: p5Types, canvasParentRef: Element) => {
      canvasParent = p5.createCanvas(width, height).parent(canvasParentRef)
      canvasParent.elt.addEventListener("mousedown", (event) => {
        console.log("EVENT FIRED----------------------------:", event)
      })
    }
```

**Comment by Hahlh** [comment]
The next question would be, how to best allow users to decide whether they would like to attach an event to the canvas element or to the global p5 object.

Maybe the easiest enhancement for the moment would be, to add the remaining p5 events to the event list (they should remain fairly static over time) and to add to the documentation, that events that get added via the props will be attached to the global p5 object and that users should use the manual method like in the example above, if they would like events to be scoped for the canvas or other elements.

**Comment by Gherciu** [comment]
@Hahlh yes, will be nice if you can find the remaining events and add them to the list in a PR.

About your workaround with mouseclick...I would propose another more let's say React related.
```js
<div onClick={this.onCamvasClick}>
  <Scketch setup={this.setup} draw={this.draw} />
</div>
```

**Comment by Gherciu** [comment]
Also in the latest version, I've added the possibility to access the event...and I've documented it.
```js
mouseClicked(_p5, event) {
  console.log(event)
  // event.preventDefault()
  // event.stopPropagation()
  // event.target
}
```

**Comment by Hahlh** [comment]
> Also in the latest version, I've added the possibility to access the event...and I've documented it.
> 
> ```js
> mouseClicked(_p5, event) {
>   console.log(event)
>   // event.preventDefault()
>   // event.stopPropagation()
>   // event.target
> }
> ```
> 
> it can be useful.....maybe the problem is that `p5` doesnt call stopPropagation or something else.....but need to test if that's the problem

Awesome, thank you, Gherciu! 
I will check, whether I can make the same behavior work directly through manipulating the event object. 

> @Hahlh yes, will be nice if you can find the remaining events and add them to the list in a PR.
> 
> About your workaround with mouseclick...I would propose another more let's say React related.
> 
> ```js
> <div onClick={this.onCamvasClick}>
>   <Scketch setup={this.setup} draw={this.draw} />
> </div>
> ```

I could imagine the props becoming quite complicated, if the ability to select the target element is added, so I find this approach reasonable :+1: .
 
Are there any direct benefits to using the props instead of adding the listeners within the component?

How would it be possible to restrict things like `isMousePressed` to a specific element like the canvas? 
Using State and the mousePressed, mouseReleased events?

**Comment by Gherciu** [comment]
@Hahlh the benefit with props is that these listeners are directly handled by `p5` and you have access to the `p5` in these methods ....outside of these prop-methods you only have access to the `window.p5` which is not the same reference as the `p5` in your sketch methods.......
But I don't know at the moment why it listens to the window but not to canvas.

**Comment by Hahlh** [comment]
> @Hahlh the benefit with props is that these listeners are directly handled by `p5` and you have access to the `p5` in these methods ....outside of these prop-methods you only have access to the `window.p5` which is not the same reference as the `p5` in your sketch methods....... I'm using `new p5(p => {})` to create a sketch....and only using prop-methods you have access to this `p`
> But I don't know at the moment why it listens to the window but not to canvas.

Here it listens to the window and therefore also events on the canvas work. Because it listens to the whole window the events fire across the whole page, but drawing happens only on the canvas.

Normally the event listener would have to be attached to the canvas itself in order to prevent the events triggering on clicks outside of the canvas, if I am understanding it right:
![image](https://user-images.githubusercontent.com/45669613/112503122-f4620580-8d8a-11eb-9146-86419660eafc.png)

**Comment by Gherciu** [comment]
@Hahlh  hmm thanks for this investigation.... so thats actually a p5 issue but not react-p5 ...
I think I will document that because everyoane is confused.

Knowing that I can refactor it and atach only on canvas these events ...but I need a list of events which should be atached to canvas and which not.

**Comment by Hahlh** [comment]
You are welcome, @Gherciu!  

For the moment I think, that attaching events in the setup function and using state for the boolean values like `isMousePressed` should cover most use cases. 

If there are any use cases, that can't be dealt with with the current setup, I am sure we can find ways to solve them :+1:
