### ISSUE TITLE
fit p5 canvas into react component

### ISSUE THREAD

**Issue by voidsailor** [Gherciu/react-p5#65]
Hi,

I'd like to render a p5 canvas inside of a react component.
Is there a convenient way to make the canvas fit the component dimensions?
My original idea was to fetch the parent component's dimensions using the useRef hook and pass them to a child that contains the p5 canvas.
But this way I alway had the problem that scroll bars were introduced and I wasn't able to hide them.

thanks in advance :)

**Comment by Gherciu** [comment]
Hi @voidsailor 
So, your idea with useRef to get parent width/height and pass to the canvas is GOOD and it definitely should work...But is strange that you get scrollbars...
Most probably you have to check your styles and which component adds these scrollbars and fix the width height of that component...

A SandBox example will be very useful for me to check the root cause to see if is a react-p5 issue or an issue related to your css styles...thx

**Comment by voidsailor** [comment]
Hi @Gherciu, it was indeed some styling-weirdness.
I could circumvent the problem by applying 100% width and height and overflow hidden to the parent container.
Additionally, I introduced a div containing the p5 "Sketch" component and set height and width by inline styling.

CodeSandbox example below:
https://codesandbox.io/s/divine-paper-f6yu5

Thanks for replying :)

**Comment by cordial** [comment]
how did you fix it @voidsailor ? Ive got same issue and cant see how to apply overflow:hidden to the Sketch - Im using styled components and trying to wrap <Sketch> doesnt work.
